FROM gcr.io/ahmetb-public/cloud-run-proxy AS tool

FROM golang:alpine AS build
WORKDIR /src/app
COPY ./sample-app .
RUN CGO_ENABLED=0 go build -o /app .

FROM alpine
RUN apk add --no-cache curl
COPY --from=tool /cloud_run_proxy /cloud_run_proxy
COPY --from=build /app /app
ENTRYPOINT ["/cloud_run_proxy", "--", "/app"]
