FROM golang:alpine AS build
WORKDIR /src/app
COPY ./sample-app .
RUN CGO_ENABLED=0 go build -o /app .

FROM alpine
RUN apk add --no-cache curl bind-tools
COPY --from=build /app /app
ADD https://github.com/ahmetb/runsd/releases/download/v0.0.0-rc.3/runsd /runsd
RUN chmod +x /runsd
ENTRYPOINT ["/runsd", "--", "/app"]
